### ISSUE TITLE
Could we make syntax highlighting work for Preview mode, too?

### ISSUE THREAD

**Issue by odiferousmint** [deathau/cm-editor-syntax-highlight-obsidian#8]
Hello.

Obsidian has some missing languages, but this plugin does not, for example: Forth. Is it possible to override Obsidian's default syntax highlighting in Preview mode with your plugin?

Or if you know how to add Forth to Obsidian's syntax highlighting, that would be much appreciated. I think they use CodeMirror, but CodeMirror supports Forth though.

**Comment by deathau** [comment]
This plugin only affects the syntax highlighting in the editor (which does use CodeMirror)

The preview uses a different thing: prism.js.

CodeMirror is great for editing, but in the preview where editing is not required, prism is much lighter (at least I assume that's why it uses something different). There could be the possibility of adding more modes to prism, but not something I've looked into.

**Comment by odiferousmint** [comment]
Ah I see. Do you have any idea how to add more languages to prism.js? Forth is missing. :/

**Comment by deathau** [comment]
Prism has requests for new languages on their github: https://github.com/PrismJS/prism/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+language%22+

If you knew what you were doing you could probably write one and submit a PR to prism (then ask Licat to pull the latest 😉). But defining syntax highlighting looks like too much regex for my brain to handle (plus I'm not familiar with Forth)
